### PR TITLE
deleted project owner from StartBuild

### PR DESCRIPTION
**Pull request by MaksymFilypchuk**

### CODE REVIEW

**Comment by VoBilyk** [comment]
What are you trying to fix?

**Comment by MaksymFilypchuk** [comment]
I tried to add ower to start build, but it not working when owner doesn't have actual github token

**Comment by MaksymFilypchuk** [comment]
> What are you trying to fix?
I tried to add ower to start build, but it not working when owner doesn't have actual github token

**Comment by MaksymFilypchuk** [comment]
do not aprove, we will discuss at a meeting how it should work

**Pull request merged**
